platform :ios, '13.0'

# Add workspace specification
workspace 'Runner.xcworkspace'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/SumSubstance/Specs.git'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Flutter pods - use the standard approach
  flutter_application_path = '../'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

# Add these permissions to Info.plist after pod install
# NSCameraUsageDescription
# NSMicrophoneUsageDescription
# NSPhotoLibraryUsageDescription
# NSLocationWhenInUseUsageDescription 